
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightASSIGNleftPLUSMINUSleftTIMESDIVIDEADD_ASSIGN ASSIGN BREAK COMMA COMMENT CONTINUE DIVIDE DIVIDE_ASSIGN ELSE EQUALS EYE FLOAT FOR GREATER GREATER_EQUALS ID IF INT LBRACE LBRACKET LESSER LESSER_EQUALS LSQUARE MDIVIDE MINUS MMINUS MPLUS MTIMES MULTIPLY_ASSIGN NOT_EQUALS ONES PLUS PRINT RANGE RBRACE RBRACKET RETURN RSQUARE SEMICOLON STRING SUBSTRACT_ASSIGN THEN TIMES TRANSPOSITION WHILE ZEROSPROGRAM : EXPRESSIONEXPRESSION : LBRACKET EXPRESSION RBRACKETEXPRESSION : INT\n                  | FLOATEXPRESSION : IDEXPRESSION : EXPRESSION PLUS EXPRESSION\n                  | EXPRESSION MINUS EXPRESSIONEXPRESSION : EXPRESSION TIMES EXPRESSION\n                  | EXPRESSION DIVIDE EXPRESSIONEXPRESSION : EXPRESSION ASSIGN EXPRESSION'
    
_lr_action_items = {'LBRACKET':([0,3,7,8,9,10,11,],[3,3,3,3,3,3,3,]),'INT':([0,3,7,8,9,10,11,],[4,4,4,4,4,4,4,]),'FLOAT':([0,3,7,8,9,10,11,],[5,5,5,5,5,5,5,]),'ID':([0,3,7,8,9,10,11,],[6,6,6,6,6,6,6,]),'$end':([1,2,4,5,6,13,14,15,16,17,18,],[0,-1,-3,-4,-5,-6,-7,-8,-9,-10,-2,]),'PLUS':([2,4,5,6,12,13,14,15,16,17,18,],[7,-3,-4,-5,7,-6,-7,-8,-9,7,-2,]),'MINUS':([2,4,5,6,12,13,14,15,16,17,18,],[8,-3,-4,-5,8,-6,-7,-8,-9,8,-2,]),'TIMES':([2,4,5,6,12,13,14,15,16,17,18,],[9,-3,-4,-5,9,9,9,-8,-9,9,-2,]),'DIVIDE':([2,4,5,6,12,13,14,15,16,17,18,],[10,-3,-4,-5,10,10,10,-8,-9,10,-2,]),'ASSIGN':([2,4,5,6,12,13,14,15,16,17,18,],[11,-3,-4,-5,11,-6,-7,-8,-9,11,-2,]),'RBRACKET':([4,5,6,12,13,14,15,16,17,18,],[-3,-4,-5,18,-6,-7,-8,-9,-10,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'PROGRAM':([0,],[1,]),'EXPRESSION':([0,3,7,8,9,10,11,],[2,12,13,14,15,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> PROGRAM","S'",1,None,None,None),
  ('PROGRAM -> EXPRESSION','PROGRAM',1,'p_program','Mparser.py',26),
  ('EXPRESSION -> LBRACKET EXPRESSION RBRACKET','EXPRESSION',3,'p_expression_brackets','Mparser.py',30),
  ('EXPRESSION -> INT','EXPRESSION',1,'p_expression_number','Mparser.py',35),
  ('EXPRESSION -> FLOAT','EXPRESSION',1,'p_expression_number','Mparser.py',36),
  ('EXPRESSION -> ID','EXPRESSION',1,'p_expression_id','Mparser.py',41),
  ('EXPRESSION -> EXPRESSION PLUS EXPRESSION','EXPRESSION',3,'p_expression_sum','Mparser.py',52),
  ('EXPRESSION -> EXPRESSION MINUS EXPRESSION','EXPRESSION',3,'p_expression_sum','Mparser.py',53),
  ('EXPRESSION -> EXPRESSION TIMES EXPRESSION','EXPRESSION',3,'p_expression_mul','Mparser.py',61),
  ('EXPRESSION -> EXPRESSION DIVIDE EXPRESSION','EXPRESSION',3,'p_expression_mul','Mparser.py',62),
  ('EXPRESSION -> EXPRESSION ASSIGN EXPRESSION','EXPRESSION',3,'p_expression_assignment','Mparser.py',69),
]
